# Generated by Django 5.0.1 on 2024-01-24 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0003_contact_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('biodegradable', 'Biodegradable Waste'), ('non_biodegradable', 'Non-Biodegradable Waste'), ('hazardous', 'Hazardous Waste'), ('recycling', 'Recycling Insights')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
