# Generated by Django 4.2.5 on 2024-02-21 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wastetypes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='biowastemodel',
            name='wastetype',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
