# Generated by Django 4.2.5 on 2024-02-21 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wastetypes', '0002_biowastemodel_wastetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='biowastemodel',
            name='phonenum',
            field=models.IntegerField(null=True),
        ),
    ]
