# Generated by Django 4.2.5 on 2024-02-22 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wastetypes', '0003_biowastemodel_phonenum'),
    ]

    operations = [
        migrations.CreateModel(
            name='HazardouswasteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('wastetype', models.CharField(max_length=100, null=True)),
                ('weight', models.IntegerField()),
                ('phonenum', models.IntegerField(null=True)),
                ('address', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NonbiowasteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('wastetype', models.CharField(max_length=100, null=True)),
                ('weight', models.IntegerField()),
                ('phonenum', models.IntegerField(null=True)),
                ('address', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.IntegerField()),
            ],
        ),
    ]
